ht1th:
  viewpara:
    nav_state: 0               #0-stop    1-towait     2-toload    3-tounload   4-reached   5-pass_light  6-wrong
    visual_state: 0            #0-close   1-light_en   2-light_dis   5-check_lane   6-lane
    pose_x: 0.0
    pose_y: 0.0
    pose_yaw: 0.0
    vel_left: 0.0
    vel_right: 0.0
    vel_angle: 0.0
  ctrlpara:
    img_sw: 0               #img_udp_transfrom_switch  false-close    true-open
    light_distance: 480000.0
    test1: 0.0
    test2: 0.0
    test3: 0.0
    test4: 0.0  
    test5: 0.0

